Readme
NASA-PDS/registry-crawler-service pull request #16
Opened 2022-02-10 00:56 UTC by tdddblog

## 🗒️ Summary
Readme file

## ♻️ Related Issues
https://github.com/NASA-PDS/pds-registry-app/issues/245

2022-02-10 03:32 UTC, nutjob4life reviewed
I'm hesitant to approve this. The issue says it needs a readme; the commit logs are just "readme", and the pull request is just "readme". That's all well and fine.

What I find a little _more_ concerning is that so much of the template repository is ripped out, especially these parts:

-   Versioning philosophy (okay not a big deal)
-   Community health (bigger deal)
    -   Contributor's guide
    -   Code of conduct
-   License (biggest deal)

The template readme gives you all these "for free" so I'm curious why it's so important _in this repository_ to **not** have this information.

I just want to double-check: is this really okay for the registry-crawler-service? @jordanpadams @tloubrieu-jpl, double-double-check?

(Haha, I think even these comments I'm typing have more lines than the actual readme! 😅)

2022-02-10 17:11 UTC, jordanpadams commented
@nutjob4life I agree here. I think some of that info may have been removed assuming it was boilerplate. will request changes...

2022-02-10 17:14 UTC, jordanpadams requested changes

2022-02-10 17:14 UTC, jordanpadams commented on README.md
> -# My Project
@tdddblog we should keep this section and just rename to what this project actually is.

2022-02-10 17:14 UTC, jordanpadams commented on README.md
> -# My Project
additionally, not going to go through the rest, but basically, all of these sections apply and should be kept and adapted, as necessary, for this repo. a lot of it can just be kept as-is (i.e. versioning = SemVer, version numbers updated, change updates, etc.) but we should definitely have them in there. especially as we are discussing using this crawler service as a more generic service capability in the future

2022-02-10 19:57 UTC, tdddblog commented on README.md
> -# My Project
Updated

2022-02-10 21:41 UTC, tloubrieu-jpl requested changes
ok,  let's not approve that, although I did approve the equivalent on registry-harvest-service.

I've added some references to the overarching application in the introduction.

@tdddblog can you elaborate the README following the intially provided template ?

Thanks

2022-02-10 21:56 UTC, tdddblog commented
@tloubrieu-jpl It was resolved and I don's see any comments after that except yours.

2022-02-11 17:38 UTC, tloubrieu-jpl approved these changes

2022-02-11 17:40 UTC, tloubrieu-jpl approved these changes

2022-02-11 17:41 UTC, merged